### ISSUE TITLE
ReferenceError: Router is not defined

### ISSUE THREAD

**Issue by rohan210** [bpoteat/meteor-html5-video#2]
I've never worked with nodejs or meteor. Was checking out the 
As per the instructions I've installed meteor and meteorite. I've also successfully installed the packages. Still I get following error. I've tried cleaning packages with mtr uninstall. Still getting the following error

Your app is crashing. Here's the latest log.

/Users/rohan210/.meteor/tools/5bf1690853/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
ReferenceError: Router is not defined
    at app/lib/router.js:20:1
    at app/lib/router.js:72:3
    at /Users/rohan210/recorder/.meteor/local/build/programs/server/boot.js:155:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/rohan210/.meteor/tools/5bf1690853/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/rohan210/recorder/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by isbkch** [comment]
You basically need to :

rm -rf packages/iron-*
rm -rf packages/iron:*
update smart.json
// smart.json
{
  "packages": {
    "iron-router": {
      "version": "0.8.2"
    },
}

Then you do a mrt add iron-router
